### ISSUE TITLE
RFC: Hydrate when visible on viewport

### ISSUE THREAD

**Issue by SoaresMG** [johannschopplich/nuxt-vitalizer#5]
### Describe the feature

Fantastic job with the module!
I started using it and the results are quite amazing.

However, my TBT went up, I'm still investigating but it seems that it might be related with more scripts being evaluated at different phases (DelayHydration + lazy).

We could expand the DelayHydration by having a "hydrate on visible"-like event, this would be super beneficial for content-heavy pages.

What do you think about it?
I can help out with the PR this week/weekend if an agreement is reached.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-vitalizer/issues).

**Comment by johannschopplich** [comment]
Hi there, 
sounds good! I don't have the resources, nor use case, to implement such a feature. Thus, PR happily welcome! 🙌

**Comment by Triloworld** [comment]
This is part of core - https://github.com/nuxt/nuxt/issues/24242#issuecomment-1857743557
This will be all in Nuxt and in Vue - https://www.youtube.com/watch?v=Pz-jnSYJnjk

**Comment by SoaresMG** [comment]
Hey @Triloworld, I commented 2 days ago the same thing on the PR.
We can close this.
