### ISSUE TITLE
Render blocking CSS still present

### ISSUE THREAD

**Issue by ejerskov** [johannschopplich/nuxt-vitalizer#8]
### Environment

- Operating System: `Darwin`
- Node Version:     `v22.6.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `pnpm@8.15.6`
- Builder:          `-`
- User Config:      `devtools`, `extends`, `routeRules`, `modules`, `vitalizer`, `i18n`, `delayHydration`, `css`, `devServer`, `runtimeConfig`, `features`, `experimental`, `nitro`, `vite`
- Runtime Modules:  `nuxt-delay-hydration@1.3.3`, `@pinia/nuxt@0.5.3`, `@nuxtjs/i18n@8.5.2`, `@nuxt/image@1.8.0`, `nuxt-vitalizer@0.10.0`
- Build Modules:    `-`

### Reproduction

I've followed these steps in the documentation:
`npx nuxi@latest module add nuxt-vitalizer`

```
// `nuxt.config.ts`
export default defineNuxtConfig({
  modules: ['nuxt-vitalizer'],

  vitalizer: {
    // Remove the render-blocking entry CSS
    disableStylesheets: 'entry'
  }
})
```

### Describe the bug

The renderblocking css is still added to head:
`<link rel="stylesheet" href="/_nuxt/entry.Cgefq8WT.css">`

PageSpeed still report it as a problem:
![image](https://github.com/user-attachments/assets/1518b130-f784-41e0-b5cf-f392f5302d13)

**Comment by ejerskov** [comment]
Okay, I've found this note deep in he source code for the `disableStylesheets` function:
```
Notes:
This requires to have the Nuxt inlineStyles feature enabled. Make sure to test your application after enabling this option.
```

Now it works, but consider adding this to the documentation.

**Comment by johannschopplich** [comment]
Thanks for the report. The documentation states [the `inlineStyles` requirement already](https://github.com/johannschopplich/nuxt-vitalizer?tab=readme-ov-file#stop-render-blocking-css).
